name: Sync Fork

on:
  schedule:
    - cron: '* 0 1 * *'
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: self-hosted
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          base: main
          head: main
